QuickSwitch 3.1.0

diff --git a/quickswitch b/quickswitch
--- a/quickswitch
+++ b/quickswitch
@@ -141,17 +141,20 @@ setvars(){
   MAGISK_VER_CODE=$(grep "MAGISK_VER_CODE=" /data/adb/magisk/util_functions.sh | awk -F = '{ print $2 }')
   if [ "$API" -ge 29 ]; then
     SUFFIX="/overlay/QuickstepSwitcherOverlay"
-    PRODUCT=true
-    # Yay, magisk supports bind mounting /product now
-    if [ $MAGISK_VER_CODE -ge "20000" ]; then
-      STEPDIR=$MODDIR/system/product$SUFFIX
-    else
-      if [ $(resetprop ro.build.version.sdk) -ge 29 ]; then
-        echo "\nMagisk v20 is required for users on Android 10"
-        echo "Please update Magisk and try again."
-        exit 1
-      fi
-    fi
+    case "$(getprop ro.product.brand) $(getprop ro.product.manufacturer) $(getprop ro.build.version.sdk)" in
+      *samsung*) STEPDIR=$MODDIR/system/vendor$SUFFIX;;
+      *) PRODUCT=true
+          # Yay, magisk supports bind mounting /product now
+          if [ $MAGISK_VER_CODE -ge "20000" ]; then
+            STEPDIR=$MODDIR/system/product$SUFFIX
+          else
+            if [ $(resetprop ro.build.version.sdk) -ge 29 ]; then
+              echo "\nMagisk v20 is required for users on Android 10"
+              echo "Please update Magisk and try again."
+              exit 1
+            fi
+          fi;;
+    esac
   else
     SUFFIX="/overlay"
     if [ -d /oem/OP ]; then
@@ -279,6 +282,19 @@ $permissions
     get_logs
     exit 1
   fi
+
+# Lets save this for a rainy day
+#  SDK=$(getprop ro.build.version.sdk)
+#  SAMMY=$(getprop ro.product.brand)
+
+#  if [[ "$SDK" = 29 ]] && \
+#     [[ "$SAMMY" == *"samsung"* ]]; then
+#    for i in $(cmd overlay list | grep navbar | awk '{print $NF}' | \
+#        egrep -v com.samsung.internal.systemui.navbar.gestural_no_hint); do
+#      cmd overlay disable $i
+#    done
+#    cmd overlay enable com.samsung.internal.systemui.navbar.gestural_no_hint
+#  fi
 
   set_perms $1
 }
