QuickSwitch 3.1.1

diff --git a/quickswitch b/quickswitch
--- a/quickswitch
+++ b/quickswitch
@@ -31,7 +31,6 @@ oldstdoutLOG=$MODDIR/logs/$ID-STDOUT-old.log
 # Start Logging verbosely
 mv -f $VERLOG $oldVERLOG 2>/dev/null; mv -f $LOG $oldLOG 2>/dev/null; mv -f $stdoutLOG $oldstdoutLOG 2>/dev/null
 exec 3>&1
-exec 1>$stdoutLOG
 exec 2>$LOG
 set -x 2>$VERLOG
 
@@ -49,6 +48,15 @@ RAND=$(echo $RANDOM | sed -r 's|^(...).*|\1|')
 QNAV=
 DID_MOUNT_RW=
 NOBACK=
+
+abort() {
+  echo "qsError: $1"
+}
+
+abortexit() {
+  echo "qsError: $1"
+  exit 1
+}
 
 # Functions to check if dirs is mounted
 is_mounted() {
@@ -148,11 +156,8 @@ setvars(){
           if [ $MAGISK_VER_CODE -ge "20000" ]; then
             STEPDIR=$MODDIR/system/product$SUFFIX
           else
-            if [ $(resetprop ro.build.version.sdk) -ge 29 ]; then
-              echo "\nMagisk v20 is required for users on Android 10"
-              echo "Please update Magisk and try again."
-              exit 1
-            fi
+            abort "Magisk v20 is required for users on Android 10"
+            abortexit "Please update Magisk and try again."
           fi;;
     esac
   else
@@ -209,9 +214,8 @@ switch_providers(){
       origdir="${sysapk}/.*.apk"
     fi
     if [ -z $sysapk ] && [ -z $dataapktmp ]; then
-      echo "\nCould not systemise launcher..."
       get_logs
-      exit 1
+      abortexit "Could not systemise launcher..."
     fi
     cp -rf $origdir \
       $SYSTEMIZE_TARGET/QuickSwitch-"${1}"-"${RAND}"/QuickSwitch-"${1}"-"${RAND}".apk
@@ -278,9 +282,8 @@ $permissions
   if [ -f ${STEPDIR}/QuickstepSwitcherOverlay.apk ]; then
     echo "\nOverlay successfully copied..."
   else
-    echo "\nThe overlay was not copied, please send logs to the developer."
     get_logs
-    exit 1
+    abortexit "The overlay was not copied, please send logs to the developer."
   fi
 
 # Lets save this for a rainy day
@@ -347,7 +350,5 @@ get_logs
 echo "\nPlease reboot for changes to take effect."
 
 exec 1>&3
-
-cat $stdoutLOG
 
 exit $?
